/**
 * Formes de base de la galerie et bornes des reglages.
 *
 * Chaque preset est un jeu complet de parametres : il n'y a aucun modele 3D
 * stocke, seulement des nombres que le generateur transforme en maillage.
 */

import type { LureParams, ShapeId } from '../types/lure';

export interface Range {
  min: number;
  max: number;
  step: number;
}

/** Bornes partagees par les sliders, la validation et l'import de projets. */
export const LIMITS = {
  length: { min: 30, max: 260, step: 1 },
  maxWidth: { min: 6, max: 80, step: 0.5 },
  thickness: { min: 6, max: 90, step: 0.5 },
  bellyPosition: { min: 0.2, max: 0.75, step: 0.01 },
  dorsalCurve: { min: -1, max: 1, step: 0.02 },
  ventralCurve: { min: -1, max: 1, step: 0.02 },
  noseSharpness: { min: 0.25, max: 1.4, step: 0.01 },
  tailTaper: { min: 0.4, max: 2.2, step: 0.01 },
  crossSection: { min: 1.4, max: 3.4, step: 0.05 },
  mouthCup: { min: 0, max: 1, step: 0.02 },
  bibAngle: { min: 10, max: 85, step: 1 },
  bibLength: { min: 5, max: 60, step: 0.5 },
  bibWidth: { min: 5, max: 50, step: 0.5 },
  tailSize: { min: 0.4, max: 1.8, step: 0.02 },
  infill: { min: 0, max: 100, step: 5 },
  hardwareMass: { min: 0, max: 20, step: 0.1 },
  ballastMass: { min: 0.1, max: 30, step: 0.1 },
  ballastPosition: { min: 0.05, max: 0.95, step: 0.01 },
  ballastHeight: { min: -1, max: 1, step: 0.05 },
  patternScale: { min: 3, max: 26, step: 1 },
  zoneLength: { min: 0, max: 0.4, step: 0.01 },
  paintBlend: { min: 0, max: 1, step: 0.02 },
  gillPosition: { min: 0.12, max: 0.5, step: 0.01 },
  gillSize: { min: 1, max: 14, step: 0.5 },
  gillRelief: { min: -2, max: 2, step: 0.05 },
  eyePosition: { min: 0.03, max: 0.3, step: 0.01 },
  eyeSize: { min: 1.5, max: 14, step: 0.5 },
  eyeRelief: { min: -2, max: 2, step: 0.05 },
  billThickness: { min: 0.5, max: 3, step: 0.1 },
  ballastDensity: { min: 7, max: 11.4, step: 0.05 },
  planeAngle: { min: 0, max: 90, step: 1 },
  tenonCount: { min: 1, max: 4, step: 1 },
  tenonDiameter: { min: 0, max: 8, step: 0.1 },
  tenonClearance: { min: 0, max: 0.4, step: 0.01 },
  boreClearance: { min: 0, max: 0.4, step: 0.01 },
  channelOffset: { min: 0.05, max: 1, step: 0.05 },
  sweepExtra: { min: 0, max: 1, step: 0.05 },
  tenonFit: { min: 0, max: 0.5, step: 0.01 },
  billFit: { min: 0, max: 0.5, step: 0.01 },
  billOffset: { min: 0, max: 30, step: 0.5 },
  billFillet: { min: 0, max: 4, step: 0.1 },
  billTwist: { min: -30, max: 30, step: 1 },
  anchorPosition: { min: 0.02, max: 0.97, step: 0.005 },
  anchorHeight: { min: -1, max: 1, step: 0.02 },
  anchorAngle: { min: 0, max: 359, step: 1 },
  anchorDepth: { min: 0, max: 8, step: 0.1 },
  sculptAmount: { min: -8, max: 8, step: 0.1 },
  sculptRadius: { min: 0.04, max: 0.35, step: 0.01 },
} as const satisfies Record<string, Range>;

export interface ShapePreset {
  id: ShapeId;
  label: string;
  tagline: string;
  description: string;
  params: LureParams;
}

const ballast = (
  position: number,
  height: number,
  mass: number,
  seed: string,
  shape: 'sphere' | 'cylinder' = 'sphere',
) => ({
  id: `${seed}-${position}`,
  position,
  height,
  mass,
  shape,
});

/**
 * Ancrages par defaut : les trois points d'attache d'un leurre classique.
 * Le fil sort vers le nez, vers le ventre et vers la queue.
 */
const defaultAnchors = (): LureParams['assembly']['anchors'] => [
  { id: 'nez', position: 0.1, height: 0, axisAngle: 0, depth: 0, pin: 'auto', method: 'bore' },
  { id: 'ventre', position: 0.44, height: -0.5, axisAngle: 90, depth: 0, pin: 'auto', method: 'bore' },
  { id: 'queue', position: 0.8, height: 0, axisAngle: 180, depth: 0, pin: 'auto', method: 'bore' },
];

/** Assemblage par defaut : joint vertical, alesage simple, trois ancrages. */
const assembly = (
  overrides: Partial<LureParams['assembly']> = {},
): LureParams['assembly'] => ({
  enabled: true,
  planeAngle: 0,
  socketMethod: 'bore',
  pin: 'auto',
  roughWater: false,
  anchors: defaultAnchors(),
  ...overrides,
});

/** Jeux de fabrication par defaut, a reajuster apres mesure sur machine. */
const fabrication = (): LureParams['fabrication'] => ({
  boreClearance: 0.05,
  channelOffset: 0.25,
  sweepExtra: 0.2,
  tenonFit: 0.15,
  billFit: 0.15,
});

export const SHAPE_PRESETS: ShapePreset[] = [
  {
    id: 'stickbait165',
    label: 'Stickbait 165',
    tagline: 'Long profil de surface, sans bavette',
    description:
      'Silhouette longue et fine relevee sur une reference reelle (160 x 32 x 21 mm). Sans bavette : c est la tete et le lestage arriere qui donnent le walking. Goupille forcee en L, regle eaux sales.',
    params: {
      shape: 'stickbait165',
      length: 160,
      maxWidth: 21,
      thickness: 32,
      bellyPosition: 0.45,
      dorsalCurve: 0.12,
      ventralCurve: 0.18,
      noseSharpness: 0.45,
      tailTaper: 1.25,
      crossSection: 2.05,
      mouthCup: 0.15,
      hasBib: false,
      billMode: 'printed',
      billThickness: 1.5,
      billOffset: 3,
      billFillet: 0.4,
      billProfile: 'rounded',
      billTwist: 0,
      bibAngle: 45,
      bibLength: 20,
      bibWidth: 18,
      tailShape: 'round',
      tailSize: 0.8,
      gills: { enabled: true, position: 0.24, size: 8, relief: -0.7 },
      eyes: { enabled: true, position: 0.09, size: 7, relief: 0.7 },
      eyeStyle: 'realistic',
      clip: 'none',
      assembly: assembly({ roughWater: true }),
      fabrication: fabrication(),
      sculpt: [],
      material: 'pla',
      infill: 10,
      hardwareMass: 5.5,
      ballastDensity: 7.9,
      ballasts: [ballast(0.5, -0.7, 6, 'stk'), ballast(0.76, -0.55, 5, 'stk')],
      paint: {
        dorsal: '#1d3f63',
        flank: '#dfe6ec',
        belly: '#ffffff',
        head: '#1d3f63',
        tail: '#dfe6ec',
        headLength: 0,
        tailLength: 0,
        blend: 0.5,
        eyeColor: '#e8b21a',
        pattern: 'scales',
        patternColor: '#8fa3b4',
        patternScale: 18,
        finish: 'gloss',
      },
    },
  },
  {
    id: 'irresistible',
    label: 'Irresistible',
    tagline: 'Compact a bavette dediee',
    description:
      'Petit profil trapu releve sur une reference reelle (57 x 15 x 13 mm assemble). Bavette dediee, corps court : nage vibrante et prospection rapide des bordures.',
    params: {
      shape: 'irresistible',
      length: 57,
      maxWidth: 12.8,
      thickness: 15,
      bellyPosition: 0.4,
      dorsalCurve: 0.3,
      ventralCurve: 0.3,
      noseSharpness: 0.4,
      tailTaper: 1.2,
      crossSection: 2.1,
      mouthCup: 0,
      hasBib: true,
      billMode: 'printed',
      billThickness: 1.2,
      billOffset: 3,
      billFillet: 0.4,
      billProfile: 'rounded',
      billTwist: 0,
      bibAngle: 45,
      bibLength: 14,
      bibWidth: 11,
      tailShape: 'round',
      tailSize: 0.7,
      gills: { enabled: true, position: 0.27, size: 4.5, relief: -0.4 },
      eyes: { enabled: true, position: 0.12, size: 3.5, relief: 0.4 },
      eyeStyle: 'realistic',
      clip: 'none',
      assembly: assembly(),
      fabrication: fabrication(),
      sculpt: [],
      material: 'pla',
      infill: 12,
      hardwareMass: 1.8,
      ballastDensity: 7.9,
      ballasts: [ballast(0.44, -0.75, 1.4, 'irr')],
      paint: {
        dorsal: '#5c3b1e',
        flank: '#d9c39a',
        belly: '#f4ece0',
        head: '#5c3b1e',
        tail: '#d9c39a',
        headLength: 0,
        tailLength: 0,
        blend: 0.45,
        eyeColor: '#e8b21a',
        pattern: 'dots',
        patternColor: '#3a2612',
        patternScale: 12,
        finish: 'satin',
      },
    },
  },
  {
    id: 'ryoshi',
    label: 'Ryoshi',
    tagline: 'Elance, type jerkbait',
    description:
      'Profil elance releve sur une reference reelle (86 x 20 x 18 mm assemble). Bavette courte et peu inclinee : depart-arret et nage serree.',
    params: {
      shape: 'ryoshi',
      length: 86,
      maxWidth: 18,
      thickness: 20,
      bellyPosition: 0.44,
      dorsalCurve: 0.22,
      ventralCurve: 0.25,
      noseSharpness: 0.5,
      tailTaper: 1.3,
      crossSection: 2.05,
      mouthCup: 0,
      hasBib: true,
      billMode: 'printed',
      billThickness: 1.5,
      billOffset: 3,
      billFillet: 0.4,
      billProfile: 'rounded',
      billTwist: 0,
      bibAngle: 38,
      bibLength: 16,
      bibWidth: 13,
      tailShape: 'forked',
      tailSize: 0.85,
      gills: { enabled: true, position: 0.25, size: 5.5, relief: -0.5 },
      eyes: { enabled: true, position: 0.1, size: 4.5, relief: 0.5 },
      eyeStyle: 'realistic',
      clip: 'none',
      assembly: assembly(),
      fabrication: fabrication(),
      sculpt: [],
      material: 'pla',
      infill: 12,
      hardwareMass: 2.8,
      ballastDensity: 7.9,
      ballasts: [ballast(0.46, -0.72, 2.6, 'ryo'), ballast(0.66, -0.6, 1.6, 'ryo')],
      paint: {
        dorsal: '#2f4f4f',
        flank: '#cfd8dc',
        belly: '#ffffff',
        head: '#2f4f4f',
        tail: '#e30613',
        headLength: 0,
        tailLength: 0.1,
        blend: 0.4,
        eyeColor: '#e8b21a',
        pattern: 'scales',
        patternColor: '#8fa3b4',
        patternScale: 14,
        finish: 'gloss',
      },
    },
  },
  {
    id: 'model25',
    label: 'Modele 1 (2.5 po)',
    tagline: 'Corps court, grande bavette',
    description:
      'Profil releve sur une reference reelle (81 x 20 x 20 mm assemble), avec sa bavette dediee. Corps haut et court : nage ample des les premiers tours de manivelle.',
    params: {
      shape: 'model25',
      length: 81,
      maxWidth: 20,
      thickness: 20,
      bellyPosition: 0.38,
      dorsalCurve: 0.35,
      ventralCurve: 0.35,
      noseSharpness: 0.4,
      tailTaper: 1.25,
      crossSection: 2.2,
      mouthCup: 0,
      hasBib: true,
      billMode: 'printed',
      billThickness: 1.5,
      billOffset: 3,
      billFillet: 0.4,
      billProfile: 'rounded',
      billTwist: 0,
      bibAngle: 50,
      bibLength: 18,
      bibWidth: 15,
      tailShape: 'round',
      tailSize: 0.75,
      gills: { enabled: true, position: 0.27, size: 5.5, relief: -0.5 },
      eyes: { enabled: true, position: 0.11, size: 4.5, relief: 0.5 },
      eyeStyle: 'realistic',
      clip: 'none',
      assembly: assembly(),
      fabrication: fabrication(),
      sculpt: [],
      material: 'pla',
      infill: 12,
      hardwareMass: 2.6,
      ballastDensity: 7.9,
      ballasts: [ballast(0.42, -0.75, 2.4, 'm25')],
      paint: {
        dorsal: '#3d6b2e',
        flank: '#e8d75c',
        belly: '#f2a33c',
        head: '#3d6b2e',
        tail: '#e8d75c',
        headLength: 0,
        tailLength: 0,
        blend: 0.45,
        eyeColor: '#e8b21a',
        pattern: 'stripes',
        patternColor: '#1f2f16',
        patternScale: 8,
        finish: 'gloss',
      },
    },
  },
  {
    id: 'minnow',
    label: 'Minnow',
    tagline: 'Poisson nageur elance',
    description:
      'Silhouette fuselee, bavette moyenne, nage serree. La forme polyvalente par excellence pour le brochet, la perche et le bar.',
    params: {
      shape: 'minnow',
      length: 110,
      maxWidth: 14,
      thickness: 22,
      bellyPosition: 0.42,
      dorsalCurve: 0.25,
      ventralCurve: 0.3,
      noseSharpness: 0.55,
      tailTaper: 1.15,
      crossSection: 2.1,
      mouthCup: 0,
      hasBib: true,
      billMode: 'printed',
      billThickness: 1.5,
      billOffset: 3,
      billFillet: 0.4,
      billProfile: 'rounded',
      billTwist: 0,
      bibAngle: 40,
      bibLength: 20,
      bibWidth: 16,
      tailShape: 'forked',
      tailSize: 0.9,
      gills: { enabled: true, position: 0.24, size: 6.0, relief: -0.6 },
      eyes: { enabled: true, position: 0.1, size: 5.0, relief: 0.6 },
      eyeStyle: 'realistic',
      clip: 'none',
      assembly: assembly(),
      fabrication: fabrication(),
      sculpt: [],
      material: 'pla',
      infill: 12,
      hardwareMass: 3.2,
      ballastDensity: 7.9,
      ballasts: [ballast(0.3, -0.7, 2, 'min'), ballast(0.52, -0.75, 4, 'min')],
      paint: {
        dorsal: '#14425E',
        flank: '#DCE6EE',
        belly: '#FFFFFF',
        head: '#0b7285',
        tail: '#dce6ee',
        headLength: 0,
        tailLength: 0,
        blend: 0.45,
        eyeColor: '#e8b21a',
        pattern: 'gradient',
        patternColor: '#0B7285',
        patternScale: 8,
        finish: 'gloss',
      },
    },
  },
  {
    id: 'popper',
    label: 'Popper',
    tagline: 'Bouche creusee, travail en surface',
    description:
      'Tete tronquee et creusee qui projette une gerbe a chaque coup de scion. Lestage arriere pour garder le nez hors de l eau.',
    params: {
      shape: 'popper',
      length: 85,
      maxWidth: 20,
      thickness: 24,
      bellyPosition: 0.3,
      dorsalCurve: 0.15,
      ventralCurve: 0.35,
      noseSharpness: 0.3,
      tailTaper: 1.5,
      crossSection: 2.2,
      mouthCup: 0.85,
      hasBib: false,
      billMode: 'printed',
      billThickness: 1.5,
      billOffset: 3,
      billFillet: 0.4,
      billProfile: 'rounded',
      billTwist: 0,
      bibAngle: 45,
      bibLength: 18,
      bibWidth: 16,
      tailShape: 'round',
      tailSize: 0.8,
      gills: { enabled: true, position: 0.26, size: 5.5, relief: -0.5 },
      eyes: { enabled: true, position: 0.11, size: 5.5, relief: 0.6 },
      eyeStyle: 'realistic',
      clip: 'none',
      assembly: assembly(),
      fabrication: fabrication(),
      sculpt: [],
      material: 'pla',
      infill: 10,
      hardwareMass: 3,
      ballastDensity: 7.9,
      ballasts: [ballast(0.58, -0.55, 3.2, 'pop'), ballast(0.7, -0.45, 1.6, 'pop')],
      paint: {
        dorsal: '#FFFFFF',
        flank: '#FFFFFF',
        belly: '#FFFFFF',
        head: '#e30613',
        tail: '#ffffff',
        headLength: 0,
        tailLength: 0,
        blend: 0.45,
        eyeColor: '#e8b21a',
        pattern: 'gradient',
        patternColor: '#E30613',
        patternScale: 8,
        finish: 'gloss',
      },
    },
  },
  {
    id: 'crankbait',
    label: 'Crankbait',
    tagline: 'Corps trapu, grande bavette',
    description:
      'Volume court et haut, bavette large tres inclinee : nage ample et vibrante, prospection rapide sur toute la couche d eau.',
    params: {
      shape: 'crankbait',
      length: 62,
      maxWidth: 17,
      thickness: 28,
      bellyPosition: 0.4,
      dorsalCurve: 0.3,
      ventralCurve: 0.34,
      noseSharpness: 0.4,
      tailTaper: 0.95,
      crossSection: 2.4,
      mouthCup: 0,
      hasBib: true,
      billMode: 'printed',
      billThickness: 1.5,
      billOffset: 3,
      billFillet: 0.4,
      billProfile: 'rounded',
      billTwist: 0,
      bibAngle: 58,
      bibLength: 26,
      bibWidth: 22,
      tailShape: 'round',
      tailSize: 0.8,
      gills: { enabled: true, position: 0.28, size: 5.0, relief: -0.5 },
      eyes: { enabled: true, position: 0.13, size: 4.5, relief: 0.6 },
      eyeStyle: 'realistic',
      clip: 'none',
      assembly: assembly(),
      fabrication: fabrication(),
      sculpt: [],
      material: 'pla',
      infill: 8,
      hardwareMass: 3.4,
      ballastDensity: 7.9,
      ballasts: [ballast(0.38, -0.8, 4.5, 'crk'), ballast(0.55, -0.7, 1.6, 'crk')],
      paint: {
        dorsal: '#2E6B1F',
        flank: '#F2C200',
        belly: '#F26A00',
        head: '#2e6b1f',
        tail: '#f2c200',
        headLength: 0,
        tailLength: 0,
        blend: 0.4,
        eyeColor: '#e8b21a',
        pattern: 'stripes',
        patternColor: '#12200E',
        patternScale: 9,
        finish: 'gloss',
      },
    },
  },
  {
    id: 'jerkbait',
    label: 'Jerkbait',
    tagline: 'Long et fin, nage erratique',
    description:
      'Corps allonge, bavette courte et peu inclinee. Concu pour les depart-arret : le suspending fige le leurre entre deux tirees.',
    params: {
      shape: 'jerkbait',
      length: 120,
      maxWidth: 13,
      thickness: 22,
      bellyPosition: 0.45,
      dorsalCurve: 0.2,
      ventralCurve: 0.2,
      noseSharpness: 0.6,
      tailTaper: 1.3,
      crossSection: 2,
      mouthCup: 0,
      hasBib: true,
      billMode: 'printed',
      billThickness: 1.5,
      billOffset: 3,
      billFillet: 0.4,
      billProfile: 'rounded',
      billTwist: 0,
      bibAngle: 32,
      bibLength: 18,
      bibWidth: 14,
      tailShape: 'forked',
      tailSize: 0.85,
      gills: { enabled: true, position: 0.22, size: 6.0, relief: -0.6 },
      eyes: { enabled: true, position: 0.09, size: 4.5, relief: 0.6 },
      eyeStyle: 'realistic',
      clip: 'none',
      assembly: assembly(),
      fabrication: fabrication(),
      sculpt: [],
      material: 'pla',
      infill: 10,
      hardwareMass: 3.6,
      ballastDensity: 7.9,
      ballasts: [ballast(0.48, -0.7, 3.7, 'jrk'), ballast(0.62, -0.65, 3, 'jrk')],
      paint: {
        dorsal: '#0E2E4F',
        flank: '#D9E2EA',
        belly: '#FFFFFF',
        head: '#b9c6d2',
        tail: '#e30613',
        headLength: 0,
        tailLength: 0.12,
        blend: 0.4,
        eyeColor: '#e8b21a',
        pattern: 'dots',
        patternColor: '#9AA7B2',
        patternScale: 16,
        finish: 'gloss',
      },
    },
  },
  {
    id: 'spoon',
    label: 'Spoon',
    tagline: 'Cuiller ondulante',
    description:
      'Lame large et plate, sans bavette : c est la section aplatie qui cree le roulis et les eclats de flanc a la descente.',
    params: {
      shape: 'spoon',
      length: 72,
      maxWidth: 26,
      thickness: 8,
      bellyPosition: 0.45,
      dorsalCurve: 0.1,
      ventralCurve: 0.1,
      noseSharpness: 0.5,
      tailTaper: 0.9,
      crossSection: 1.8,
      mouthCup: 0,
      hasBib: false,
      billMode: 'printed',
      billThickness: 1.5,
      billOffset: 3,
      billFillet: 0.4,
      billProfile: 'rounded',
      billTwist: 0,
      bibAngle: 45,
      bibLength: 15,
      bibWidth: 14,
      tailShape: 'fan',
      tailSize: 0.6,
      gills: { enabled: false, position: 0.25, size: 5.0, relief: -0.5 },
      eyes: { enabled: false, position: 0.1, size: 4.0, relief: 0.5 },
      eyeStyle: 'realistic',
      clip: 'none',
      assembly: assembly(),
      fabrication: fabrication(),
      sculpt: [],
      material: 'resin',
      infill: 100,
      hardwareMass: 2.6,
      ballastDensity: 7.9,
      ballasts: [],
      paint: {
        dorsal: '#E30613',
        flank: '#FFFFFF',
        belly: '#E30613',
        head: '#e30613',
        tail: '#e30613',
        headLength: 0,
        tailLength: 0,
        blend: 0.3,
        eyeColor: '#e8b21a',
        pattern: 'stripes',
        patternColor: '#E30613',
        patternScale: 5,
        finish: 'chrome',
      },
    },
  },
  {
    id: 'swimbait',
    label: 'Swimbait',
    tagline: 'Gros volume, queue palette',
    description:
      'Corps de poisson fourrage imposant termine par une palette souple. Imprime en TPU, la queue bat des la moindre traction.',
    params: {
      shape: 'swimbait',
      length: 135,
      maxWidth: 24,
      thickness: 38,
      bellyPosition: 0.4,
      dorsalCurve: 0.45,
      ventralCurve: 0.4,
      noseSharpness: 0.45,
      tailTaper: 1.6,
      crossSection: 2.2,
      mouthCup: 0,
      hasBib: false,
      billMode: 'printed',
      billThickness: 1.5,
      billOffset: 3,
      billFillet: 0.4,
      billProfile: 'rounded',
      billTwist: 0,
      bibAngle: 45,
      bibLength: 20,
      bibWidth: 18,
      tailShape: 'paddle',
      tailSize: 1,
      gills: { enabled: true, position: 0.26, size: 9.0, relief: -0.9 },
      eyes: { enabled: true, position: 0.11, size: 7.0, relief: 0.9 },
      eyeStyle: 'realistic',
      clip: 'none',
      assembly: assembly(),
      fabrication: fabrication(),
      sculpt: [],
      material: 'tpu',
      infill: 25,
      hardwareMass: 4.5,
      ballastDensity: 7.9,
      ballasts: [ballast(0.42, -0.7, 18, 'swb'), ballast(0.6, -0.65, 11.5, 'swb')],
      paint: {
        dorsal: '#3E5C43',
        flank: '#C9C3B4',
        belly: '#F2EDE4',
        head: '#3e5c43',
        tail: '#8e8676',
        headLength: 0,
        tailLength: 0.15,
        blend: 0.5,
        eyeColor: '#e8b21a',
        pattern: 'dots',
        patternColor: '#2A2A24',
        patternScale: 14,
        finish: 'satin',
      },
    },
  },
  {
    id: 'topwater',
    label: 'Topwater',
    tagline: 'Stickbait de surface',
    description:
      'Cigare sans bavette, leste sur l arriere : la tete pivote a chaque tiree pour un walking the dog regulier.',
    params: {
      shape: 'topwater',
      length: 105,
      maxWidth: 18,
      thickness: 20,
      bellyPosition: 0.55,
      dorsalCurve: 0.1,
      ventralCurve: 0.15,
      noseSharpness: 0.4,
      tailTaper: 1.1,
      crossSection: 2,
      mouthCup: 0.25,
      hasBib: false,
      billMode: 'printed',
      billThickness: 1.5,
      billOffset: 3,
      billFillet: 0.4,
      billProfile: 'rounded',
      billTwist: 0,
      bibAngle: 45,
      bibLength: 16,
      bibWidth: 14,
      tailShape: 'round',
      tailSize: 0.7,
      gills: { enabled: true, position: 0.24, size: 5.5, relief: -0.5 },
      eyes: { enabled: true, position: 0.1, size: 5.0, relief: 0.6 },
      eyeStyle: 'realistic',
      clip: 'none',
      assembly: assembly(),
      fabrication: fabrication(),
      sculpt: [],
      material: 'lwpla',
      infill: 100,
      hardwareMass: 3,
      ballastDensity: 7.9,
      ballasts: [ballast(0.85, -0.4, 1.5, 'top')],
      paint: {
        dorsal: '#F2F4F6',
        flank: '#FFFFFF',
        belly: '#FFFFFF',
        head: '#e30613',
        tail: '#ffffff',
        headLength: 0.22,
        tailLength: 0,
        blend: 0.35,
        eyeColor: '#e8b21a',
        pattern: 'none',
        patternColor: '#111315',
        patternScale: 8,
        finish: 'satin',
      },
    },
  },
];

export const getPreset = (id: ShapeId): ShapePreset =>
  SHAPE_PRESETS.find((preset) => preset.id === id) ?? SHAPE_PRESETS[0];

/** Copie profonde : les presets ne doivent jamais etre modifies en place. */
export const clonePreset = (id: ShapeId): LureParams => {
  const { params } = getPreset(id);
  return {
    ...params,
    ballasts: params.ballasts.map((b, i) => ({ ...b, id: `${b.id}-${i}-${Date.now()}` })),
    gills: { ...params.gills },
    eyes: { ...params.eyes },
    assembly: {
      ...params.assembly,
      anchors: params.assembly.anchors.map((anchor, i) => ({
        ...anchor,
        id: `${anchor.id}-${i}-${Date.now()}`,
      })),
    },
    fabrication: { ...params.fabrication },
    sculpt: params.sculpt.map((point) => ({ ...point })),
    paint: { ...params.paint },
  };
};
